### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by coder1165** [open-kf/rag-gpt#81]
I create environment python==3.18;
after copy env_of_deepseek to .env
run sh strat.sh
Then ImportError occurred.
How should i fix it?

(five) (five) c_cxl@node2:/storage/c_cxl/game/five_AI/rag-gpt-main$ sh start.sh
Create tables in the SQLite database
Create indexes for the tables
Initialize the admin account
[INFO] account_name:'admin' already exists.
Initialize the bot settings
[INFO] the bot setting already exists.
SQLite init Done!

Init Chroma DB
2024-10-14 16:02:37.413 | INFO     | server.rag.index.embedder.document_embedder:__init__:46 - [DOC_EMBEDDER] init, collection_name: 'mychroma_collection', persist_directory: 'chroma_dir', llm_name: 'DeepSeek'
Init Chroma DB Done!
[2024-10-14 16:02:46 +0800] [13824] [INFO] Starting gunicorn 21.2.0
[2024-10-14 16:02:46 +0800] [13824] [INFO] Listening at: http://0.0.0.0:7000 (13824)
[2024-10-14 16:02:46 +0800] [13824] [INFO] Using worker: sync
[2024-10-14 16:02:46 +0800] [13829] [INFO] Booting worker with pid: 13829
[2024-10-14 16:02:46 +0800] [13830] [INFO] Booting worker with pid: 13830
[2024-10-14 16:02:46 +0800] [13831] [INFO] Booting worker with pid: 13831
[2024-10-14 16:02:49 +0800] [13829] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/storage/c_cxl/game/five_AI/rag-gpt-main/five/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/storage/c_cxl/game/five_AI/rag-gpt-main/five/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/storage/c_cxl/game/five_AI/rag-gpt-main/five/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/storage/c_cxl/game/five_AI/rag-gpt-main/five/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/storage/c_cxl/game/five_AI/rag-gpt-main/five/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/storage/c_cxl/game/five_AI/rag-gpt-main/five/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/storage/c_cxl/game/five_AI/rag-gpt-main/five/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/storage/c_cxl/miniconda3/envs/five/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/storage/c_cxl/game/five_AI/rag-gpt-main/rag_gpt_app.py", line 12, in <module>
    from server.app import account, auth, bot_config, common, files, intervention, queries, sitemaps, urls
  File "/storage/c_cxl/game/five_AI/rag-gpt-main/server/app/files.py", line 21, in <module>
    from server.rag.index.parser.file_loader.csv_loader import AsyncCsvLoader
  File "/storage/c_cxl/game/five_AI/rag-gpt-main/server/rag/index/parser/file_loader/csv_loader.py", line 2, in <module>
    from llama_parse import LlamaParse
  File "/storage/c_cxl/game/five_AI/rag-gpt-main/five/lib/python3.10/site-packages/llama_parse/__init__.py", line 1, in <module>
    from llama_parse.base import LlamaParse, ResultType
  File "/storage/c_cxl/game/five_AI/rag-gpt-main/five/lib/python3.10/site-packages/llama_parse/base.py", line 11, in <module>
    from llama_index.core.bridge.pydantic import Field, validator
ImportError: cannot import name 'validator' from 'llama_index.core.bridge.pydantic' (/storage/c_cxl/game/five_AI/rag-gpt-main/five/lib/python3.10/site-packages/llama_index/core/bridge/pydantic.py)
[2024-10-14 16:02:49 +0800] [13829] [INFO] Worker exiting (pid: 13829)
[2024-10-14 16:02:49 +0800] [13830] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/storage/c_cxl/game/five_AI/rag-gpt-main/five/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/storage/c_cxl/game/five_AI/rag-gpt-main/five/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/storage/c_cxl/game/five_AI/rag-gpt-main/five/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/storage/c_cxl/game/five_AI/rag-gpt-main/five/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/storage/c_cxl/game/five_AI/rag-gpt-main/five/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/storage/c_cxl/game/five_AI/rag-gpt-main/five/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/storage/c_cxl/game/five_AI/rag-gpt-main/five/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/storage/c_cxl/miniconda3/envs/five/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/storage/c_cxl/game/five_AI/rag-gpt-main/rag_gpt_app.py", line 12, in <module>
    from server.app import account, auth, bot_config, common, files, intervention, queries, sitemaps, urls
  File "/storage/c_cxl/game/five_AI/rag-gpt-main/server/app/files.py", line 21, in <module>
    from server.rag.index.parser.file_loader.csv_loader import AsyncCsvLoader
  File "/storage/c_cxl/game/five_AI/rag-gpt-main/server/rag/index/parser/file_loader/csv_loader.py", line 2, in <module>
    from llama_parse import LlamaParse
  File "/storage/c_cxl/game/five_AI/rag-gpt-main/five/lib/python3.10/site-packages/llama_parse/__init__.py", line 1, in <module>
    from llama_parse.base import LlamaParse, ResultType
  File "/storage/c_cxl/game/five_AI/rag-gpt-main/five/lib/python3.10/site-packages/llama_parse/base.py", line 11, in <module>
    from llama_index.core.bridge.pydantic import Field, validator
ImportError: cannot import name 'validator' from 'llama_index.core.bridge.pydantic' (/storage/c_cxl/game/five_AI/rag-gpt-main/five/lib/python3.10/site-packages/llama_index/core/bridge/pydantic.py)
[2024-10-14 16:02:49 +0800] [13830] [INFO] Worker exiting (pid: 13830)
[2024-10-14 16:02:49 +0800] [13831] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/storage/c_cxl/game/five_AI/rag-gpt-main/five/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/storage/c_cxl/game/five_AI/rag-gpt-main/five/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/storage/c_cxl/game/five_AI/rag-gpt-main/five/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/storage/c_cxl/game/five_AI/rag-gpt-main/five/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/storage/c_cxl/game/five_AI/rag-gpt-main/five/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/storage/c_cxl/game/five_AI/rag-gpt-main/five/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/storage/c_cxl/game/five_AI/rag-gpt-main/five/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/storage/c_cxl/miniconda3/envs/five/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/storage/c_cxl/game/five_AI/rag-gpt-main/rag_gpt_app.py", line 12, in <module>
    from server.app import account, auth, bot_config, common, files, intervention, queries, sitemaps, urls
  File "/storage/c_cxl/game/five_AI/rag-gpt-main/server/app/files.py", line 21, in <module>
    from server.rag.index.parser.file_loader.csv_loader import AsyncCsvLoader
  File "/storage/c_cxl/game/five_AI/rag-gpt-main/server/rag/index/parser/file_loader/csv_loader.py", line 2, in <module>
    from llama_parse import LlamaParse
  File "/storage/c_cxl/game/five_AI/rag-gpt-main/five/lib/python3.10/site-packages/llama_parse/__init__.py", line 1, in <module>
    from llama_parse.base import LlamaParse, ResultType
  File "/storage/c_cxl/game/five_AI/rag-gpt-main/five/lib/python3.10/site-packages/llama_parse/base.py", line 11, in <module>
    from llama_index.core.bridge.pydantic import Field, validator
ImportError: cannot import name 'validator' from 'llama_index.core.bridge.pydantic' (/storage/c_cxl/game/five_AI/rag-gpt-main/five/lib/python3.10/site-packages/llama_index/core/bridge/pydantic.py)
[2024-10-14 16:02:49 +0800] [13831] [INFO] Worker exiting (pid: 13831)
[2024-10-14 16:02:49 +0800] [13824] [ERROR] Worker (pid:13829) exited with code 3
[2024-10-14 16:02:49 +0800] [13824] [ERROR] Worker (pid:13830) was sent SIGTERM!
[2024-10-14 16:02:49 +0800] [13824] [ERROR] Worker (pid:13831) was sent SIGTERM!
[2024-10-14 16:02:49 +0800] [13824] [ERROR] Shutting down: Master
[2024-10-14 16:02:49 +0800] [13824] [ERROR] Reason: Worker failed to boot.

**Comment by blmdxiao** [comment]
Please check whether the version of llama_index matches that of llama_parse.

**Comment by LinYuXuan168** [comment]
"pip install -U llama_pares" works
